jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
      REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
    steps:
    - uses: actions/checkout@v4

    # Outras etapas do build

    # Etapa para depurar variáveis de ambiente
    - run: |
        echo "AWS_REGION: $AWS_REGION"
        echo "BUCKET_S3: $BUCKET_S3"
        echo "REGISTRY_URL: $REGISTRY_URL"
        echo "MODULE_FULLNAME: $MODULE_FULLNAME"

    - run: aws s3 cp frontend/.next/server/app s3://$BUCKET_S3 --recursive --acl public-read
